this = '123456'
print('this:')
print('.', this, '.')
print('ljust 1:')
print('.', this.ljust(1), '.')
print('ljust 2:')
print('.', this.ljust(2), '.')
print('ljust 6:')
print('.', this.ljust(6), '.')
print('ljust 8:')
print('.', this.ljust(8), '.')
print('rjust 1')
print('.', this.rjust(1), '.')
print('rjust 2')
print('.', this.rjust(2), '.')
print('rjust 6:')
print('.', this.rjust(6), ',')
print('rjust 8:')
print('.', this.rjust(8), '.')
